CREATE DATABASE databaseusers;
USE databaseusers;
CREATE TABLE usersregistered(
    id INT(6) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    user VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL 
)AUTO_INCREMENT=1;